import type { JurisprudenceRecord } from "@/types/jurisprudence";

/**
 * Fase 1: catálogo curado en código.
 * Fase 2: migrar a `jurisprudence_documents` vía repository Supabase.
 */
export const JURISPRUDENCE_SEED: JurisprudenceRecord[] = [
  {
    id: "cas-1465-2007-lima",
    title: "Casación 1465-2007-Lima",
    tipo: "casacion",
    materia: "civil",
    submateria: "Interpretación del Acto Jurídico",
    year: 2007,
    organo: "Sala Civil Permanente — Corte Suprema",
    summary:
      "La Corte Suprema precisa que la simulación absoluta genera nulidad absoluta del acto disimulado, pues no existe voluntad negocial real. La interpretación del acto jurídico debe reconstruir la verdadera intención de las partes cuando el negocio aparente encubre una simulación.",
    keywords: [
      "simulación absoluta",
      "simulación",
      "acto jurídico",
      "interpretación del acto jurídico",
      "nulidad",
      "voluntad negocial",
    ],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "1465-2007-Lima",
  },
  {
    id: "cas-2841-2012-lima",
    title: "Casación 2841-2012-Lima",
    tipo: "casacion",
    materia: "civil",
    submateria: "Simulación Relativa",
    year: 2012,
    organo: "Sala Civil Transitoria — Corte Suprema",
    summary:
      "En la simulación relativa el acto simulado es válido y solo el acto disimulado produce efectos jurídicos entre las partes. La prueba de la simulación corresponde a quien la alega, con indicio grave y preciso.",
    keywords: ["simulación relativa", "simulación", "acto jurídico", "prueba", "eficacia"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "2841-2012-Lima",
  },
  {
    id: "cas-512-2015-lima",
    title: "Casación 512-2015-Lima",
    tipo: "casacion",
    materia: "civil",
    submateria: "Acto Jurídico — Elementos",
    year: 2015,
    organo: "Sala Civil Permanente — Corte Suprema",
    summary:
      "Reitera que el acto jurídico exige consentimiento, objeto y causa lícita. La ausencia de causa simulada en negocios onerosos permite presumir simulación cuando concurren indicios concurrentes de disimulo.",
    keywords: ["acto jurídico", "consentimiento", "causa", "objeto", "simulación"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "512-2015-Lima",
  },
  {
    id: "cas-1890-2018-lima",
    title: "Casación 1890-2018-Lima",
    tipo: "casacion",
    materia: "civil",
    submateria: "Responsabilidad Civil Extracontractual",
    year: 2018,
    organo: "Sala Civil Permanente — Corte Suprema",
    summary:
      "La responsabilidad civil extracontractual exige acción u omisión antijurídica, daño y nexo causal. El quantum indemnizatorio debe ser proporcional al daño efectivamente acreditado, incluido el daño moral cuando procede.",
    keywords: ["responsabilidad civil", "daño", "nexo causal", "indemnización", "extracontractual"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "1890-2018-Lima",
  },
  {
    id: "cas-334-2020-lima",
    title: "Casación 334-2020-Lima",
    tipo: "casacion",
    materia: "civil",
    submateria: "Buena Fe Contractual",
    year: 2020,
    organo: "Sala Civil Permanente — Corte Suprema",
    summary:
      "La buena fe contractual impone deberes de información, lealtad y cooperación durante la ejecución del contrato. Su vulneración puede generar responsabilidad por incumplimiento culposo aun sin cláusula expresa.",
    keywords: ["buena fe contractual", "contrato", "deberes anexos", "incumplimiento"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "334-2020-Lima",
  },
  {
    id: "tf-012345-2019-2-1800",
    title: "Resolución del Tribunal Fiscal N.° 012345-2019-2-1800",
    tipo: "resolucion",
    materia: "tributario",
    submateria: "Compensación Tributaria",
    year: 2019,
    organo: "Tribunal Fiscal",
    summary:
      "El Tribunal Fiscal confirma que la compensación tributaria procede cuando concurren créditos y débitos líquidos y exigibles del mismo sujeto, respetando el orden cronológico y los plazos de prescripción aplicables.",
    keywords: ["compensación tributaria", "crédito fiscal", "débito fiscal", "SUNAT", "prescripción"],
    pdfUrl: "https://www.sunat.gob.pe/legislacion/jurisprudencia/",
    expediente: "012345-2019-2-1800",
  },
  {
    id: "tf-09876-2021-4-2000",
    title: "Resolución del Tribunal Fiscal N.° 09876-2021-4-2000",
    tipo: "resolucion",
    materia: "tributario",
    submateria: "Deducibilidad de Gastos",
    year: 2021,
    organo: "Tribunal Fiscal",
    summary:
      "Para la deducibilidad del gasto se exige que sea necesario para generar renta, acreditado fehacientemente y vinculado al giro del contribuyente. La mera emisión de comprobante no sustituye la prueba de la operación real.",
    keywords: ["deducibilidad", "gastos", "renta", "acreditación", "tributario"],
    pdfUrl: "https://www.sunat.gob.pe/legislacion/jurisprudencia/",
    expediente: "09876-2021-4-2000",
  },
  {
    id: "tc-00007-2006-pa-tc",
    title: "Sentencia del Tribunal Constitucional — Exp. 00007-2006-PA/TC",
    tipo: "sentencia",
    materia: "constitucional",
    submateria: "Derechos Fundamentales — Tutela",
    year: 2006,
    organo: "Tribunal Constitucional",
    summary:
      "La acción de amparo protege derechos constitucionales frente a actos u omisiones de autoridad o particulares en supuestos legales. Procede cuando no existen vías ordinarias idóneas o cuando la lesión es directa e inmediata.",
    keywords: ["derechos fundamentales", "amparo", "tutela", "TC", "constitucional"],
    pdfUrl: "https://www.tc.gob.pe/jurisprudencia/",
    expediente: "00007-2006-PA/TC",
  },
  {
    id: "tc-00220-2011-pi-tc",
    title: "Sentencia del Tribunal Constitucional — Exp. 00220-2011-PI/TC",
    tipo: "sentencia",
    materia: "constitucional",
    submateria: "Libertad Contractual y Dignidad",
    year: 2011,
    organo: "Tribunal Constitucional",
    summary:
      "El TC vincula la libertad contractual con la dignidad humana y la buena fe. Las cláusulas abusivas que desequilibran la posición del consumidor pueden ser inaplicadas por contravenir la Constitución.",
    keywords: ["libertad contractual", "dignidad", "cláusulas abusivas", "buena fe", "constitucional"],
    pdfUrl: "https://www.tc.gob.pe/jurisprudencia/",
    expediente: "00220-2011-PI/TC",
  },
  {
    id: "pv-001-2021-pj",
    title: "Precedente Vinculante N.° 001-2021-PJ-CSJ",
    tipo: "precedente_vinculante",
    materia: "procesal",
    submateria: "Valor Probatorio de Resoluciones Judiciales",
    year: 2021,
    organo: "Corte Suprema — Pleno",
    summary:
      "Establece criterio vinculante sobre la fuerza probatoria de resoluciones judiciales firmes en procesos distintos, delimitando cuándo producen cosa juzgada material o simple efecto persuasivo.",
    keywords: ["precedente vinculante", "cosa juzgada", "prueba", "procesal"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "001-2021-PJ-CSJ",
  },
  {
    id: "sent-labor-4455-2019-lima",
    title: "Sentencia Laboral 4455-2019-Lima",
    tipo: "sentencia",
    materia: "laboral",
    submateria: "Despido Fraudulento",
    year: 2019,
    organo: "Sala Laboral Permanente — Corte Suprema",
    summary:
      "Configura despido fraudulento cuando el empleador disimula una causal inexistente o falsea hechos para encubrir un despido arbitrario. Procede la reinstalación o indemnización según elección del trabajador.",
    keywords: ["despido fraudulento", "despido arbitrario", "reinstalación", "laboral"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "4455-2019-Lima",
  },
  {
    id: "exp-adm-120-2020-lima",
    title: "Expediente Administrativo 120-2020-Lima",
    tipo: "expediente",
    materia: "administrativo",
    submateria: "Silencio Administrativo Positivo",
    year: 2020,
    organo: "Tribunal de Contrataciones del Estado",
    summary:
      "Analiza los supuestos de silencio administrativo positivo en procedimientos de contratación pública y los límites cuando existe observación pendiente de subsanación por el administrado.",
    keywords: ["silencio administrativo", "contrataciones", "procedimiento", "administrativo"],
    pdfUrl: "https://www.osce.gob.pe/consultas/informacion/jurisprudencia",
    expediente: "120-2020-Lima",
  },
  {
    id: "cas-901-2016-lima",
    title: "Casación 901-2016-Lima",
    tipo: "casacion",
    materia: "penal",
    submateria: "Tipicidad y Antijuridicidad",
    year: 2016,
    organo: "Sala Penal Permanente — Corte Suprema",
    summary:
      "La tipicidad penal exige conducta descrita por la ley con descripción clara e inequívoca. La antijuridicidad material puede excluir punibilidad en supuestos de ausencia de lesión al bien jurídico.",
    keywords: ["tipicidad", "antijuridicidad", "penal", "bien jurídico"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "901-2016-Lima",
  },
  {
    id: "cas-1567-2014-lima",
    title: "Casación 1567-2014-Lima",
    tipo: "casacion",
    materia: "procesal",
    submateria: "Nulidad Procesal — Casación",
    year: 2014,
    organo: "Sala Civil Permanente — Corte Suprema",
    summary:
      "La casación por nulidad procesal requiere indefensión real y no meramente formal. Debe acreditarse que la irregularidad impidió ejercer el derecho de defensa de manera efectiva.",
    keywords: ["nulidad procesal", "casación", "indefensión", "procesal"],
    pdfUrl: "https://juris.pj.gob.pe/jurisprudenciaweb/faces/page/conDetalleJurisprudencia.xhtml",
    expediente: "1567-2014-Lima",
  },
];

export function getJurisprudenceSeedById(id: string): JurisprudenceRecord | undefined {
  return JURISPRUDENCE_SEED.find((record) => record.id === id);
}
